### ISSUE TITLE
[BUG]: Pay in advance with invoiceable: false

### ISSUE THREAD

**Issue by andrasszommer** [getlago/lago-api#2133]
**Describe the bug**
When I try to create a scenario in which we want to test an advance payment, and I don't want to issue an invoice for every event (`invoiceable: false`), the calculated amount is simply not included in the next month's fees.

**To Reproduce**
1. Set up a recurring metric
2. Set up a monthly plan, with advance payment and a charge with `invoiceable false` and `proration true`

**Expected behavior**
- We collect events from users every month within the interval of the given plan (let's say monthly).
- On the first day of the following month, the following month should be billed in ADVANCE based on the previous month's usage data.
-  **When invoiceable is true** (and we issue invoices immediately after each event), the monthly invoice fee always increases according the usage. _Which I think is the good behavior._
- **When invoiceable is false** (when we do not always want to issue an invoice, only on the first day of the month, in advance), the usage data is never included in the invoice, only the basic fee (monthly fee) is invoiced. 

I may be wrong with this, but I think this should work as described above.
If the "invoiceable false" means that these measurements will never be on the invoices, then:
- what is the best approach for my described scenario? 
- why the frontend application says "Turn it off to avoid generating an invoice for each event."

-----
I expect the following:
- The user registers for a subscription in 2024.06.05, and he pays an advance fee for the month (10 euros) 
- The backend system sends events for seats:
   - 2024.06.10: 10 new seats are added (5 euro / seat prorated) -> the user will NOT receive any invoices for this (about 41.6 euros of usage will be billed - 25/30 * 5 EUR * 10)
   - 2024.06.30: 5 new seats are added (5 euro / seat prorated) -> the user will NOT receive any invoices for this  (about 4.16 euros of usage will be billed - 5/30 * 5 EUR * 5)
- 2024.07.05: the first billing period ends, the system sends (41.66 + 4.16) + 10 euros (in advance) invoice

Currently Lago only sends the 10 euro invoice in advance, and does not use the previous usage. 

**Additional context**
[This PR](https://github.com/getlago/lago-api/pull/2087) may be related to this issue (but this PR didn't solve it)

I also created a [PR for this specific scenario](https://github.com/getlago/lago-api/pull/2132).

**I also know that this is a premium feature**, but I need to run these scenarios to determine if Lago Premium is suitable for our desired solution or not. 

**Version**
- Lago: v1.5

**Comment by mathieu-lago** [comment]
Hi @andrasszommer - sorry for the late reply. When `invoiceable` is `false`, there are no invoices for the corresponding events (i.e. no invoice when the event is ingested and no invoice when a new period starts).

In the scenario described above, the charge linked to `seats` is:

- `"pay_in_advance": false` because there's no fee when the event is ingested, the customer is only billed at the end of the month;
- `"invoiceable": true` because you do want to issue an invoice for all seats; and
- `"prorated": false` because the fee needs to be prorated based on the timestamp of your events.

So the invoice issued on 2024-07-05 includes:

- The subscription fee paid in advance for the period 2024-07-05 to 2024-08-04; and
- The usage-based charge for seats (paid in arrears) for the period 2024-06-05 to 2024-07-04.

Hope this helps.
