### ISSUE TITLE
[BUG]: Trying to issue a credit note for an invoice get feature_unavailable

### ISSUE THREAD

**Issue by sudo-sand** [getlago/lago-api#691]
**Describe the bug**
I'm trying to issue a credit note for an invoice and I get back internal error and `feature_unavailable`

```
{
    "data": {
        "createCreditNote": null
    },
    "errors": [
        {
            "message": "Internal error",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createCreditNote"
            ],
            "extensions": {
                "status": 500,
                "code": "feature_unavailable"
            }
        }
    ]
}
```

**To Reproduce**
1. Go to an invoice
2. Click on top-right drop down and pick issue a credit note
3. Enter all the info and click Issue credit note

**Version**
- Lago: v0.19.2

**Comment by mathieu-lago** [comment]
Hi @sudo-sand - the credit note feature is indeed in beta. We had to make it visible since some credit notes are automatically generated by Lago and users need to access them.

For instance, if a customer is on a plan with a subscription fee that was paid in advance and then upgrades to a plan with a subscription fee to be paid in arrears, then the billing system will automatically issue a credit note for the unused amount related to the initial subscription.

Automatic credit notes are available to everyone. However, you shouldn't be able to create a credit note manually, so I'll ask the team to disable access to this section of the app. Sorry for the inconvenience.

**Comment by mathieu-lago** [comment]
The credit note feature should be released in January. The free open-source version will give you access to automatically generated credit notes (see previous example), however, the ability to manually create credit notes (via the dropdown menu) will be a premium feature.

**Comment by omar2205** [comment]
:( is there a way to issue a refund then?
